---
abstract: 'Namespaced, error-checked I/O'
author:
  - 'Felipe Gasper <felipe@cpanel.net>'
build_requires:
  Test::Class: '0.41'
  Test::Deep: '0.114'
  Test::NoWarnings: '0.01'
  perl: '5.008'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: IO-Die
provides:
  IO::Die:
    file: lib/IO/Die.pm
    version: '0.055'
requires:
  perl: '5.006'
resources:
  license: http://opensource.org/licenses/artistic-license-2.0.php
version: '0.055'
x_serialization_backend: 'CPAN::Meta::YAML version 0.016'
